Add database
MrWhiteShapi/java-filmorate pull request #10
Opened 2024-06-08 07:21 UTC by MrWhiteShapi

Реализовано ТЗ12. Все тесты в Postman пройдены. Жду вправок...

2024-06-09 15:17 UTC, YazykovMikhail requested changes

2024-06-09 15:17 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.setMpa(mpaDB.getMPAofFilm(film.getId()));
Мпа получай сразу в запросе sql во время полчения фильма и сразу создавай фильм уже с MPA
Что ьы уменьшить количество запрсоов к БД

2024-06-09 15:17 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/films_logic/FilmGenreDB.java
> +public class FilmGenreDB implements FilmGenreStorage {
Стораджи создаются на основании сущностей, сущности FilmGenre нет, вынеси методы по поиску/добавлению жанров в GenreDB

2024-06-09 15:17 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Map<Integer, Set<Genre>> filmsGenres = filmGenreDB.findGenreOfFilm(List.of(film));
Вот тут отлично, из за того что связь многие ко многим

2024-06-09 15:17 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new NoSuchElementException("Фильма с ID=" + film.get().getId() + " нет в базе");
Если film.isEmpty() то film.get().getId() тут будет NPE
 throw new NoSuchElementException("Фильма с ID=" + id+ " нет в базе"); - вот так
 А еще лучше:
`         Film film = filmsDB.getFilmById(id).orElseThrow(() -> new NoSuchElementException("Фильма с ID=" + id + " нет в базе"));
`

2024-06-10 16:26 UTC, MrWhiteShapi commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    @Max(value = 6)
там в постмане есть тест который на выброс ошибки в случае если запрашивает жанр с айди 9999
я не хотел городить отдельный метод валидации и поэтому все сделал через спринг аннотацию

2024-06-11 14:25 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    @Max(value = 6)
хм, раньше такого не было, окей

2024-06-11 14:27 UTC, YazykovMikhail approved these changes

2024-06-14 11:59 UTC, merged