Controllers films users
MrWhiteShapi/java-filmorate pull request #6
Opened 2024-02-12 16:49 UTC by MrWhiteShapi

Реализовал все требования из тз за исключением задания со звездочкой. Я бы сначала предпочел сначала закончить с обязательной частью.

2024-02-12 17:36 UTC, dgumich requested changes

2024-02-12 17:36 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw exception;
Странная логика, словить исключение для того, что бы потом его выбросить. На самом деле эксепшн обрабатываются по другому. Вот, можешь почитать https://struchkov.dev/blog/ru/exception-handling-controlleradvice/

2024-02-12 17:36 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } catch (ValidationException exception) {
Аналогично, странная логика поймать и бросить исключение. Как обрабатывают исключение в случае веб приложения можешь почитать по ссылке, которую скинул. Если же отойти от веб приложения и хендлеров, то делают 1) Ловят проверяемое исключение и выбрасывают не проверяемое, кастомное.  Так мы избавляемся от необходимости прописать исключения, которые выбрасывает метод + делаем более специфичным. 2) Ловят исключение, логируют + делают какую-нибудь другую логику. Просто поймать, что бы выбросить его снова - так не делают=)

2024-02-12 17:36 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            makeUserLoginAlsoName(user);
Добавь логирование в самом начале метода, а то вдруг пользователь не пройдет валидацию, то мы и не залогируем ничего

2024-02-12 17:36 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            Validator.userValidation(user);
Аналогично, добавь логирование в начале метода

2024-02-12 17:36 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
Советую разобраться с валидацией в спринге. Проще чем кажется (по сути добавить зависимость и нужные аннотации), зато сильно помогает.

2024-02-13 20:44 UTC, MrWhiteShapi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw exception;
Здравствуйте, это исправил и теперь в коде @ExceptionHandler

2024-02-13 20:44 UTC, MrWhiteShapi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            Validator.userValidation(user);
тоже исправил :)

2024-02-13 20:46 UTC, MrWhiteShapi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
С валидацией действительно оказалось легче чем я думал. Самой большой сложностью в тз оказалось разобраться как работать с пул реквест.  Я внес вправки в тот же день и думал у вас автоматически обновится мой request и уже дальше по программе прошел ))))

2024-02-13 20:47 UTC, MrWhiteShapi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
Последний commit - *1f13dea*.

2024-02-13 22:04 UTC, dgumich approved these changes

2024-02-13 22:04 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @ExceptionHandler(ValidationException.class)
Сейчас это взрыв мозга=) @ExceptionHandler указывает на метод, который должен обрабатывать данное исключение. Что у тебя происходит? Метод может выбросить исключение и спринг будет думать, что этот же метод, в котором произошло исключение должно его обработать. В общем это не правильно=) Еще раз почитай ссылку, которую скинул в прошлую проверку. Плюс вот еще материал по исключениям
https://www.baeldung.com/exception-handling-for-rest-with-spring
В этой работе это не является частью ТЗ, так что мучить не буду. Но в следующей надо будет разобраться.

2024-02-25 06:49 UTC, closed without merging